version: '3.8'
services:
  app:
    build: .
    container_name: my_admin_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admin-service-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: saparAI05
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_DB: admin-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saparAI05
    ports:
      - "5432:5432"
